defaultPortal: Guest-checkout
portals:
  - name: Guest-checkout
    portalId: 6412394
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNSVoaeUMBIJAA0AAAAAAAwDGOqwhwMg15iPDCju6QwyFLQ5W2MQRsMIuHeAUpqYz-gYkhJHOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAAAAADwAAAYAAABgAAAAAAAAAAAAAAAAADACQhQJnvHvtspYuGI4xHu4_2_e68b37koDbmExUgBaAA
        expiresAt: '2022-06-08T20:01:23.160Z'
    personalAccessKey: >-
      CiQyMWMyMTE5Yy1mNTk5LTQ2MWMtYjcyOC0zNmE2ZGE0ZmVmNjAQ6rCHAxjXmI8MKhkABeaRgmJRDX3U_UjwtdRz8_63CBIAvABnSgNuYTE
