defaultPortal: Guest-checkout
portals:
  - name: Guest-checkout
    portalId: 6412394
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CKrXz_n8LxIJAA0AAAAAAAwDGOqwhwMg15iPDCju6QwyFAzYPj63vn0R3RsWH2-4DKNJN7K6OigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAAAAADwAAAYAAABgQhTAKGJvndVA87d8hN7lwtTIds4eEUoDbmExUgBaAA
        expiresAt: '2022-03-28T06:26:00.757Z'
    personalAccessKey: >-
      CiQyMWMyMTE5Yy1mNTk5LTQ2MWMtYjcyOC0zNmE2ZGE0ZmVmNjAQ6rCHAxjXmI8MKhkABeaRgmJRDX3U_UjwtdRz8_63CBIAvABnSgNuYTE
