defaultPortal: Pj20
portals:
  - name: Pj20
    portalId: 20363859
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPD5x43eLxIJAAkAAAAA4A0DGNP02gkg15iPDCju6QwyFCgapOEnqfGydJIYs4945p_7c6YuOigAAABBAAAAeAAAAAAAAAAAAAAAAAAAAAAAAMAHAP7_MTwAAAYAAABgQhQ5oSgHQK6HcIEGNrdTYOWmM3pJ-koDbmExUgBaAA
        expiresAt: '2021-12-22T10:31:18.006Z'
    personalAccessKey: >-
      CiQ2OTg4MThhMy1hMGUyLTRhNGMtODMwNS00ZWI5MzI4NWIyM2YQ0_TaCRjXmI8MKhkABeaRghpURfSYsEqB8AuTJY6xpKX9MVnySgNuYTE
