defaultPortal: Guest-checkout
portals:
  - name: Guest-checkout
    portalId: 6412394
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMTYgsb2LxIJAA0AAAAAAAwDGOqwhwMg15iPDCju6QwyFPytZTmObR3TO5Cacbvn9GdXnUIOOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAAAAADwAAAYAAABgQhQBHJw4hHvg5cch56-VItPuxJGvUEoDbmExUgBaAA
        expiresAt: '2022-03-08T08:58:51.847Z'
    personalAccessKey: >-
      CiQyMWMyMTE5Yy1mNTk5LTQ2MWMtYjcyOC0zNmE2ZGE0ZmVmNjAQ6rCHAxjXmI8MKhkABeaRgmJRDX3U_UjwtdRz8_63CBIAvABnSgNuYTE
