defaultPortal: Guest-checkout
portals:
  - name: Guest-checkout
    portalId: 6412394
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJKBheSKMBIJAA0AAAAAAAwDGOqwhwMg15iPDCju6QwyFLBSWBqzVpWombrPpl3t6z8dFRGuOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAAAAADwAAAYAAABgAAAAAAAAAAAAAAAAADACQhTEwYuLMn98W7EaxbEYkcE6eOgDYkoDbmExUgBaAA
        expiresAt: '2022-05-10T05:46:33.493Z'
    personalAccessKey: >-
      CiQyMWMyMTE5Yy1mNTk5LTQ2MWMtYjcyOC0zNmE2ZGE0ZmVmNjAQ6rCHAxjXmI8MKhkABeaRgmJRDX3U_UjwtdRz8_63CBIAvABnSgNuYTE
