defaultPortal: Guest-checkout
portals:
  - name: Guest-checkout
    portalId: 6412394
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMDqm-_2LxIJAA0AAAAAAAwDGOqwhwMg15iPDCju6QwyFHV8--wVHPoKprM8ZTGkw6kY9zS9OigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAAAAADwAAAYAAABgQhQgkC61pV-kGspywHEreM66xmQwq0oDbmExUgBaAA
        expiresAt: '2022-03-09T08:58:46.980Z'
    personalAccessKey: >-
      CiQyMWMyMTE5Yy1mNTk5LTQ2MWMtYjcyOC0zNmE2ZGE0ZmVmNjAQ6rCHAxjXmI8MKhkABeaRgmJRDX3U_UjwtdRz8_63CBIAvABnSgNuYTE
