defaultPortal: Guest-checkout
portals:
  - name: Guest-checkout
    portalId: 6412394
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COasu-mdMBIJAA0AAAAAAAwDGOqwhwMg15iPDCju6QwyFG2xOhK7h7R_ctjWy7EDObICQ6WjOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAAAAADwAAAYAAABgAAAAAAAAAAAAAAAAADACQhThtRTOWfHuCdpdE_4zSoK__Y31jUoDbmExUgBaAA
        expiresAt: '2022-07-08T09:40:43.241Z'
    personalAccessKey: >-
      CiQyMWMyMTE5Yy1mNTk5LTQ2MWMtYjcyOC0zNmE2ZGE0ZmVmNjAQ6rCHAxjXmI8MKhkABeaRgmJRDX3U_UjwtdRz8_63CBIAvABnSgNuYTE
